APPLICATION_GOOD_BODY = {
    'information': {
        'first_name': 'Andrew James',
        'last_name': 'McLeod',
        'date_of_birth': '1987-03-04',
        'addresses': [
            {
                'address': '3023 BODEGA ROAD',
                'city': 'VICTORIA',
                'province_state': 'BC',
                'country': 'CA',
            }
        ],
    }
}

AUTH_RESPONSE = {
    'token': 'e5e4c777acb3c2a4e4234a282a8ac507c0be24708e6dfe121de563dda397784b',
    'user_id': 'b8959d81-89aa-4e3e-9a5a-66f46bad591b',
}

AUTH_RESPONSE_FAIL = {'detail': 'Invalid username/password.'}

AUTH_RESPONSE_LIST_LOGINS = [
    {'created': '2019-03-01T18:56:34.702679Z', 'expires': None, 'token_key': 'e21e9b59'}
]

LISTING_RESPONSE = {
    'id': '86dd2316-f31d-4f5e-86a1-3a5e91a75a8c',
    'created': '2019-03-01T14:34:32.753995Z',
    'modified': '2019-03-01T14:34:32.949006Z',
    'last_updated': '2019-03-01T14:34:32.754044Z',
    'name': None,
    'unit': None,
    'move_in_date': None,
    'move_in_immediately': False,
    'rent': '1000.00',
    'rent_range': None,
    'security_deposit_amount': None,
    'pet_deposit': False,
    'pet_deposit_amount': None,
    'storage_locker': False,
    'property_manager_terms': None,
    'is_active': True,
    'is_public': False,
    'url_code': '86dd2316-f31d-4f5e-86a1-3a5e91a75a8c',
    'is_placeholder': False,
    'owner': {
        'id': 'b8959d81-89aa-4e3e-9a5a-66f46bad591b',
        'email': '***********************',
        'team': {
            'id': 'c7105cf6-0ae6-4d0b-9373-45f3c25b83f5',
            'name': 'Bungalow',
            'country': 'CA',
            'industry': '',
            'team_type': 'PM',
            'app_url': 'https://demo-app.certn.co/',
            'settings_config': {
                'get_org_name': 'Bungalow',
                'org_name': 'Bungalow',
                'org_logo_link': None,
                'org_primary_color': None,
                'behavioural_test_req': False,
                'emergency_contact_req': False,
                'personal_ref_req': False,
                'education_req': False,
                'tenancy_years_amount_req': 2,
                'tenancy_ref_amount_req': 1,
                'tenancy_ref_email_req': False,
                'tenancy_ref_phone_req': True,
                'employer_records_amount_req': 1,
                'employer_years_amount_req': 0,
                'employer_ref_req': True,
                'employer_ref_email_req': False,
                'employer_ref_phone_req': False,
                'document_required': False,
                'cover_letter_req': False,
                'government_id_req': True,
                'proof_of_income_req': True,
                'resume_req': False,
                'personal_ref_amount_req': 1,
                'request_base': True,
                'request_behavioural': True,
                'request_softcheck': True,
                'request_equifax': False,
                'request_identity_verification': False,
                'request_enhanced_identity_verification': False,
                'request_criminal_record_check': False,
                'request_enhanced_criminal_record_check': False,
                'request_motor_vehicle_records': False,
                'request_education_verification': False,
                'request_employment_verification_3_yrs': False,
                'request_employment_verification_5_yrs': False,
                'request_employment_verification_7_yrs': False,
                'request_us_criminal_softcheck': False,
                'request_us_ssn_verification': False,
                'request_employer_references': True,
                'request_address_references': True,
                'exclude_softcheck_possible_matches': False,
            },
            'billing_plan': {
                'pm_softcheck_price': '9.99',
                'hr_softcheck_price': '9.99',
                'pm_equifax_price': '14.99',
                'hr_equifax_price': '14.99',
                'pm_identity_verification_price': '1.99',
                'hr_identity_verification_price': '1.99',
                'pm_enhanced_identity_verification_price': '4.99',
                'hr_enhanced_identity_verification_price': '4.99',
                'pm_criminal_record_check_price': '29.99',
                'hr_criminal_record_check_price': '29.99',
                'pm_motor_vehicle_records_price': '24.99',
                'hr_motor_vehicle_records_price': '24.99',
                'pm_us_criminal_softcheck_price': '14.99',
                'hr_us_criminal_softcheck_price': '14.99',
                'pm_us_ssn_verification_price': '4.99',
                'hr_us_ssn_verification_price': '4.99',
                'pm_education_verification_price': '14.99',
                'hr_education_verification_price': '14.99',
                'pm_credential_verification_price': '14.99',
                'hr_credential_verification_price': '14.99',
                'pm_employment_verification_3_yrs_price': '14.99',
                'hr_employment_verification_3_yrs_price': '14.99',
                'pm_employment_verification_5_yrs_price': '19.99',
                'hr_employment_verification_5_yrs_price': '19.99',
                'pm_employment_verification_7_yrs_price': '22.99',
                'hr_employment_verification_7_yrs_price': '22.99',
                'pm_us_criminal_record_check_tier_1_price': '15.00',
                'hr_us_criminal_record_check_tier_1_price': '15.00',
                'pm_us_criminal_record_check_tier_2_price': '30.00',
                'hr_us_criminal_record_check_tier_2_price': '30.00',
                'pm_us_criminal_record_check_tier_3_price': '40.00',
                'hr_us_criminal_record_check_tier_3_price': '40.00',
                'pm_employer_references_price': '4.99',
                'pm_address_references_price': '4.99',
                'pm_education_references_price': '4.99',
                'pm_credential_references_price': '4.99',
                'hr_employer_references_price': '4.99',
                'hr_address_references_price': '4.99',
                'hr_education_references_price': '4.99',
                'hr_credential_references_price': '4.99',
            },
        },
    },
    'property': {
        'id': 'ef834890-ce60-4b95-bee9-69a12c59d4f8',
        'status': 'N',
        'get_status_display': 'No Vacancy',
        'created': '2019-03-01T14:34:32.601691Z',
        'modified': '2019-03-01T14:34:32.601720Z',
        'last_updated': '2019-03-01T14:34:32.601755Z',
        'building': None,
        'building_code': None,
        'address': '123 Fakestreet',
        'city': 'Victoria',
        'province_state': 'BC',
        'country': 'N',
        'postal_code': None,
        'is_active': True,
        'owner': {
            'id': 'b8959d81-89aa-4e3e-9a5a-66f46bad591b',
            'email': '************************',
            'team': {
                'id': 'c7105cf6-0ae6-4d0b-9373-45f3c25b83f5',
                'name': 'Bungalow',
                'country': 'CA',
                'industry': '',
                'team_type': 'PM',
                'app_url': 'https://demo-app.certn.co/',
                'settings_config': {
                    'get_org_name': 'Bungalow',
                    'org_name': 'Bungalow',
                    'org_logo_link': None,
                    'org_primary_color': None,
                    'behavioural_test_req': False,
                    'emergency_contact_req': False,
                    'personal_ref_req': False,
                    'education_req': False,
                    'tenancy_years_amount_req': 2,
                    'tenancy_ref_amount_req': 1,
                    'tenancy_ref_email_req': False,
                    'tenancy_ref_phone_req': True,
                    'employer_records_amount_req': 1,
                    'employer_years_amount_req': 0,
                    'employer_ref_req': True,
                    'employer_ref_email_req': False,
                    'employer_ref_phone_req': False,
                    'document_required': False,
                    'cover_letter_req': False,
                    'government_id_req': True,
                    'proof_of_income_req': True,
                    'resume_req': False,
                    'personal_ref_amount_req': 1,
                    'request_base': True,
                    'request_behavioural': True,
                    'request_softcheck': True,
                    'request_equifax': False,
                    'request_identity_verification': False,
                    'request_enhanced_identity_verification': False,
                    'request_criminal_record_check': False,
                    'request_enhanced_criminal_record_check': False,
                    'request_motor_vehicle_records': False,
                    'request_education_verification': False,
                    'request_employment_verification_3_yrs': False,
                    'request_employment_verification_5_yrs': False,
                    'request_employment_verification_7_yrs': False,
                    'request_us_criminal_softcheck': False,
                    'request_us_ssn_verification': False,
                    'request_employer_references': True,
                    'request_address_references': True,
                    'exclude_softcheck_possible_matches': False,
                },
                'billing_plan': {
                    'pm_softcheck_price': '9.99',
                    'hr_softcheck_price': '9.99',
                    'pm_equifax_price': '14.99',
                    'hr_equifax_price': '14.99',
                    'pm_identity_verification_price': '1.99',
                    'hr_identity_verification_price': '1.99',
                    'pm_enhanced_identity_verification_price': '4.99',
                    'hr_enhanced_identity_verification_price': '4.99',
                    'pm_criminal_record_check_price': '29.99',
                    'hr_criminal_record_check_price': '29.99',
                    'pm_motor_vehicle_records_price': '24.99',
                    'hr_motor_vehicle_records_price': '24.99',
                    'pm_us_criminal_softcheck_price': '14.99',
                    'hr_us_criminal_softcheck_price': '14.99',
                    'pm_us_ssn_verification_price': '4.99',
                    'hr_us_ssn_verification_price': '4.99',
                    'pm_education_verification_price': '14.99',
                    'hr_education_verification_price': '14.99',
                    'pm_credential_verification_price': '14.99',
                    'hr_credential_verification_price': '14.99',
                    'pm_employment_verification_3_yrs_price': '14.99',
                    'hr_employment_verification_3_yrs_price': '14.99',
                    'pm_employment_verification_5_yrs_price': '19.99',
                    'hr_employment_verification_5_yrs_price': '19.99',
                    'pm_employment_verification_7_yrs_price': '22.99',
                    'hr_employment_verification_7_yrs_price': '22.99',
                    'pm_us_criminal_record_check_tier_1_price': '15.00',
                    'hr_us_criminal_record_check_tier_1_price': '15.00',
                    'pm_us_criminal_record_check_tier_2_price': '30.00',
                    'hr_us_criminal_record_check_tier_2_price': '30.00',
                    'pm_us_criminal_record_check_tier_3_price': '40.00',
                    'hr_us_criminal_record_check_tier_3_price': '40.00',
                    'pm_employer_references_price': '4.99',
                    'pm_address_references_price': '4.99',
                    'pm_education_references_price': '4.99',
                    'pm_credential_references_price': '4.99',
                    'hr_employer_references_price': '4.99',
                    'hr_address_references_price': '4.99',
                    'hr_education_references_price': '4.99',
                    'hr_credential_references_price': '4.99',
                },
            },
        },
        'listing_count': 1,
        'full_address': '123 Fakestreet Victoria BC N ',
        'url_code': 'ef834890-ce60-4b95-bee9-69a12c59d4f8',
    },
    'applicant_count': 0,
    'new_applicant_count': 0,
    'is_psychometric_required': True,
    'notification_list': [],
    'selected_application': None,
    'use_team_link': False,
    'length_of_lease': None,
}

LISTINGS_LIST_RESPONSE = {
    'count': 1,
    'next': 'http://demo-api.certn.co/api/v2/listings/?page=2',
    'previous': None,
    'results': [LISTING_RESPONSE],
}

INVITE_BODY = {'email': 'fake@fake.com', 'email_applicants': False}

QUICK_RESPONSE = {
    'notes': None,
    'is_favourite': False,
    'has_viewed_listing': None,
    'is_viewed': False,
    'id': 'db13d65c-4311-46e7-8d4d-97feb693e113',
    'created': '2019-03-04T14:51:24.323137Z',
    'modified': '2019-03-04T14:51:24.582378Z',
    'submitted_time': '2019-03-04T14:51:24.468514Z',
    'last_updated': '2019-03-04T14:51:24.323304Z',
    'status': 'Analyzing',
    'applicant_type': 'Quick Screen',
    'monthly_cost': None,
    'is_equifax_eligible': True,
    'certn_score_label': 'NONE',
    'is_submitted': True,
    'softcheck_discounted': False,
    'equifax_discounted': False,
    'is_cosigner': False,
    'email_references': False,
    'tenancy_verified': None,
    'employment_verified': None,
    'employment_verification': 'NONE',
    'certn_score': None,
    'late_rent_potential': None,
    'damage_to_property': None,
    'eviction_potential': None,
    'tenancy_length': None,
    'late_rent_potential_label': 'None',
    'damage_to_property_label': 'None',
    'eviction_potential_label': 'None',
    'tenancy_length_label': 'None',
    'applicant_account': {'id': 'bf5080d0-7f73-4c8f-9cbd-afcf54450962', 'email': None},
    'application': {
        'id': 'd799e68f-3491-4645-95c7-8f42b3c2976d',
        'created': '2019-03-04T14:51:24.318595Z',
        'modified': '2019-03-04T14:51:24.591766Z',
        'owner': {
            'id': 'b8959d81-89aa-4e3e-9a5a-66f46bad591b',
            'email': '*******************',
            'team': {
                'id': 'c7105cf6-0ae6-4d0b-9373-45f3c25b83f5',
                'name': 'Bungalow',
                'country': 'CA',
                'industry': '',
                'team_type': 'PM',
                'app_url': 'https://demo-app.certn.co/',
                'settings_config': {
                    'get_org_name': 'Bungalow',
                    'org_name': 'Bungalow',
                    'org_logo_link': None,
                    'org_primary_color': None,
                    'behavioural_test_req': False,
                    'emergency_contact_req': False,
                    'personal_ref_req': False,
                    'education_req': False,
                    'tenancy_years_amount_req': 2,
                    'tenancy_ref_amount_req': 1,
                    'tenancy_ref_email_req': False,
                    'tenancy_ref_phone_req': True,
                    'employer_records_amount_req': 1,
                    'employer_years_amount_req': 0,
                    'employer_ref_req': True,
                    'employer_ref_email_req': False,
                    'employer_ref_phone_req': False,
                    'document_required': False,
                    'cover_letter_req': False,
                    'government_id_req': True,
                    'proof_of_income_req': True,
                    'resume_req': False,
                    'personal_ref_amount_req': 1,
                    'request_base': True,
                    'request_behavioural': True,
                    'request_softcheck': True,
                    'request_equifax': False,
                    'request_identity_verification': False,
                    'request_enhanced_identity_verification': False,
                    'request_criminal_record_check': False,
                    'request_enhanced_criminal_record_check': False,
                    'request_motor_vehicle_records': False,
                    'request_education_verification': False,
                    'request_employment_verification_3_yrs': False,
                    'request_employment_verification_5_yrs': False,
                    'request_employment_verification_7_yrs': False,
                    'request_us_criminal_softcheck': False,
                    'request_us_ssn_verification': False,
                    'request_employer_references': True,
                    'request_address_references': True,
                    'exclude_softcheck_possible_matches': False,
                },
                'billing_plan': {
                    'pm_softcheck_price': '9.99',
                    'hr_softcheck_price': '9.99',
                    'pm_equifax_price': '14.99',
                    'hr_equifax_price': '14.99',
                    'pm_identity_verification_price': '1.99',
                    'hr_identity_verification_price': '1.99',
                    'pm_enhanced_identity_verification_price': '4.99',
                    'hr_enhanced_identity_verification_price': '4.99',
                    'pm_criminal_record_check_price': '29.99',
                    'hr_criminal_record_check_price': '29.99',
                    'pm_motor_vehicle_records_price': '24.99',
                    'hr_motor_vehicle_records_price': '24.99',
                    'pm_us_criminal_softcheck_price': '14.99',
                    'hr_us_criminal_softcheck_price': '14.99',
                    'pm_us_ssn_verification_price': '4.99',
                    'hr_us_ssn_verification_price': '4.99',
                    'pm_education_verification_price': '14.99',
                    'hr_education_verification_price': '14.99',
                    'pm_credential_verification_price': '14.99',
                    'hr_credential_verification_price': '14.99',
                    'pm_employment_verification_3_yrs_price': '14.99',
                    'hr_employment_verification_3_yrs_price': '14.99',
                    'pm_employment_verification_5_yrs_price': '19.99',
                    'hr_employment_verification_5_yrs_price': '19.99',
                    'pm_employment_verification_7_yrs_price': '22.99',
                    'hr_employment_verification_7_yrs_price': '22.99',
                    'pm_us_criminal_record_check_tier_1_price': '15.00',
                    'hr_us_criminal_record_check_tier_1_price': '15.00',
                    'pm_us_criminal_record_check_tier_2_price': '30.00',
                    'hr_us_criminal_record_check_tier_2_price': '30.00',
                    'pm_us_criminal_record_check_tier_3_price': '40.00',
                    'hr_us_criminal_record_check_tier_3_price': '40.00',
                    'pm_employer_references_price': '4.99',
                    'pm_address_references_price': '4.99',
                    'pm_education_references_price': '4.99',
                    'pm_credential_references_price': '4.99',
                    'hr_employer_references_price': '4.99',
                    'hr_address_references_price': '4.99',
                    'hr_education_references_price': '4.99',
                    'hr_credential_references_price': '4.99',
                },
            },
        },
        'listing': None,
        'property': None,
        'status': 'Complete',
        'applicants': [
            {
                'id': '72af8e90-832f-4aee-89e4-3bcf090aa758',
                'status': 'Analyzing',
                'first_name': 'Andrew James',
                'last_name': 'McLeod',
                'email': None,
                'certn_score': None,
                'share_of_rent': None,
                'is_cosigner': False,
                'application_url': None,
                'report_url': (
                    'https://demo-app.certn.co/pm/applications/'
                    '72af8e90-832f-4aee-89e4-3bcf090aa758/'
                ),
            }
        ],
        'is_active': True,
        'is_selected': False,
        'applicant_status': 'N',
        'get_applicant_status_display': 'None',
    },
    'behavioural_result_summary': (
        'The Behavioural score is determined by '
        'analysing psychometric personality tests,'
        ' social media analysis, and more.'
    ),
    'information': {
        'id': '9de408e3-6fa8-4520-b772-236c674a885d',
        'created': '2019-03-04T14:51:24.302393Z',
        'modified': '2019-03-04T14:51:24.335917Z',
        'id_url': None,
        'id_file_name': None,
        'first_name': 'Andrew James',
        'last_name': 'McLeod',
        'middle_name': None,
        'employers': [],
        'applicant_created': False,
        'applicant_verified': False,
        'educations': [],
        'cover_letter': None,
        'addresses': [
            {
                'id': '15d7a997-9b4a-4825-b853-2d8276f2892b',
                'created': '2019-03-04T14:51:24.307633Z',
                'current': True,
                'address': '3023 BODEGA ROAD',
                'unit': None,
                'rent_or_own': 'R',
                'city': 'VICTORIA',
                'province_state': 'BC',
                'country': 'CA',
                'postal_code': None,
                'cost': None,
                'start_date': None,
                'end_date': None,
                'reason_for_leaving': 'N',
                'landlords_first_name': None,
                'landlords_last_name': None,
                'landlords_phone': None,
                'landlords_email': None,
                'reference': None,
                'full_address': ' 3023 BODEGA ROAD VICTORIA BC CA',
                'information': {'first_name': 'Andrew James', 'last_name': 'McLeod'},
                'address_reference': None,
                'other_reason_for_leaving': None,
                'auto_address': None,
                'place_id': None,
                'verification': None,
                'consistency': None,
                'rent_or_own_label': 'Rent',
                'reference_verified': False,
                'other_province_state': None,
                'county': None,
            }
        ],
        'date_of_birth': '1987-03-04',
        'phone_number': None,
        'co_signer': None,
        'applicant_account': {'id': 'bf5080d0-7f73-4c8f-9cbd-afcf54450962', 'email': None},
        'co_signer_living_with_applicant': None,
        'co_signer_association': 'N',
        'co_signer_first_name': None,
        'co_signer_last_name': None,
        'co_signer_email': None,
        'co_signer_phone': None,
        'car': None,
        'car_make': None,
        'car_model': None,
        'car_year': None,
        'car_color': None,
        'health_insurance_label': 'No Coverage',
        'car_prov_state': None,
        'car_plate': None,
        'smoke': None,
        'conviction_explanation': None,
        'personal_reference_association_label': 'None',
        'bankruptcy_explanation': None,
        'eviction_explanation': None,
        'status': 'C',
        'rent_refusal_explanation': None,
        'health_insurance': 'NC',
        'feedback': None,
        'pets': None,
        'license_number': None,
        'license_valid': None,
        'license_prov_state': None,
        'pets_type': None,
        'emergency_contact': False,
        'emergency_contact_first_name': None,
        'emergency_contact_last_name': None,
        'emergency_contact_email': None,
        'expected_tenancy_length': None,
        'personal_reference': False,
        'emergency_contact_phone': None,
        'personal_reference_first_name': None,
        'personal_reference_last_name': None,
        'personal_reference_phone': None,
        'personal_reference_email': None,
        'personal_reference_association': 'N',
        'occupants': [],
        'sin_ssn': None,
        'facebook_link': None,
        'twitter_link': None,
        'linkedin_link': None,
        'googleplus_link': None,
        'desired_move_in_date': None,
        'skills': [],
        'documents': [],
        'pet_details': [],
        'rent_refusals': [],
        'bankruptcies': [],
        'evictions': [],
        'convictions': [],
        'co_signer_association_label': 'None',
        'former_names': None,
        'last_name_at_birth': None,
        'alias': None,
        'gender': None,
        'birth_city': None,
        'birth_province_state': None,
        'birth_country': None,
        'birth_other_province_state': None,
        'personal_references': [],
        'terms_accepted': False,
        'rcmp_consent_given': False,
        'co_signer_report_url': None,
        'phone': None,
    },
    'psychometric_test': None,
    'facebook': None,
    'linkedin': None,
    'informational_result': None,
    'behavioural_result': None,
    'risk_result': {
        'id': 'dfec7632-e148-4e5c-a6f9-e018a802d75b',
        'status': 'NONE',
        'overall_score': 'NONE',
        'risk_evaluations': [],
        'red_flags': None,
        'green_flags': None,
        'description': (
            'The social score is based on self-provided information from the '
            'applicant and an analysis of the applicants information available '
            'to Certn. This includes a criminal identity scan, social profile '
            'scan, as well as other important informational data points. *Note '
            'that when criminal identities are discovered the overall Certn '
            'score is not impacted by the results found unless the match '
            'similarity is above our confidence threshold of 95%.'
        ),
        'risk_description': (
            'The criminal identity risk is an assessment of the risk posed to '
            'assets given the results of the criminal identity scan. Please '
            'review any risk relevant information from our negative news and '
            'criminal database analysis below.'
        ),
        'similarity_description': (
            'The criminal identity similarity percentage is a comparison between '
            'the applicants self-provided information and the corresponding '
            'information we find in our databases. As a general guideline, if '
            'the results of our criminal identity scan has a similarity '
            'percentage of above 95%, Certn can confidently predict that the '
            'information presented below corresponds correctly to the applicant '
            'being screened. However, if the criminal identity scan returns results '
            'with a similarity percentage below 95%, the onus falls to the client '
            'to accurately verify the results.'
        ),
        'match_description': (
            'The criminal identity Match Score is a comparison between the '
            'applicants self-provided information and the corresponding '
            'information we find in our databases. As a general guideline, if '
            'the results of our criminal identity scan finds a "Likely Match", '
            'Certn can confidently predict that the information presented '
            'below corresponds correctly to the applicant being screened. '
            'However, if the criminal identity scan returns reasults with a '
            'Match Score of "Possible Match", the onus falls on the client to '
            'accurately verify the results.'
        ),
    },
    'equifax_result': None,
    'identity_verification': None,
    'enhanced_identity_verification': None,
    'manual_id_verification': None,
    'late_rent_potential_description': (
        'Late rent potential risk is assessed using an analysis of an '
        'applicants financial stability and / or behavioural credibility '
        'characteristics that predicts the likelihood of late or missed payments.'
    ),
    'damage_to_property_description': (
        'Damage to property risk is assessed using an analysis of an applicants '
        'personal history and / or behavioural cleanliness and neighbour '
        'characteristics that predicts the likelihood of causing damage to property.'
    ),
    'eviction_potential_description': (
        'Early vacancy risk if assessed using an analysis of an applicants '
        'tenancy history and / or behavioural stability characteristics that '
        'predicts the likelihood of breaking a lease.'
    ),
    'applicant_result_description': (
        'Certn Rating and Certn Score is a summary assessment of the applicants '
        'unique characteristics and personal information. Andrew James McLeod '
        'has received a Certn rating of "NONE" which indicates an analysis with '
        'no potential issues. Although the score is a summary assessment, Certn '
        'still recommends you carefully review each section of this report to '
        'determine if the applicant meets your specific requirements.'
    ),
    'applicant_result_summary': (
        'The Applicant score is determined by analysing tenancy history, '
        'employment history, and more.'
    ),
    'social_result_summary': (
        'The Social score is determined by analysing criminal identity, negative '
        'news, social profile scans, and more.'
    ),
    'financial_result_summary': (
        'The Financial score is determined by analysing an Equifax credit check, '
        'and more.'
    ),
    'identity_verified': None,
    'identity_verified_summary': (
        'Upgrade Certn Report to verify Andrew James McLeods identity.'
    ),
    'request_equifax': False,
    'request_softcheck': True,
    'request_identity_verification': False,
    'request_criminal_record_check': False,
    'request_motor_vehicle_records': False,
    'request_behavioural': True,
    'request_enhanced_identity_verification': False,
    'request_education_verification': False,
    'request_credential_verification': False,
    'request_employment_verification_3_yrs': False,
    'request_employment_verification_5_yrs': False,
    'request_employment_verification_7_yrs': False,
    'can_upgrade': True,
    'reference_result': None,
    'tag': None,
    'comments': [],
    'request_us_criminal_softcheck': False,
    'request_us_ssn_verification': False,
    'country': 'CA',
    'request_employer_references': True,
    'request_address_references': True,
    'request_us_criminal_record_check_tier_1': False,
    'request_us_criminal_record_check_tier_2': False,
    'request_us_criminal_record_check_tier_3': False,
    'us_criminal_record_check_result': None,
}

APPLICANT_GET_RESPONSE = {
    'notes': None,
    'is_favourite': False,
    'has_viewed_listing': None,
    'is_viewed': False,
    'id': 'db13d65c-4311-46e7-8d4d-97feb693e113',
    'created': '2019-03-04T17:00:38.684380Z',
    'modified': '2019-03-04T17:00:38.919122Z',
    'submitted_time': '2019-03-04T17:00:38.837847Z',
    'last_updated': '2019-03-04T17:00:38.684535Z',
    'status': 'Analyzing',
    'applicant_type': 'Quick Screen',
    'monthly_cost': None,
    'is_equifax_eligible': True,
    'certn_score_label': 'NONE',
    'is_submitted': True,
    'softcheck_discounted': False,
    'equifax_discounted': False,
    'is_cosigner': False,
    'email_references': False,
    'tenancy_verified': None,
    'employment_verified': None,
    'employment_verification': 'NONE',
    'certn_score': None,
    'late_rent_potential': None,
    'damage_to_property': None,
    'eviction_potential': None,
    'tenancy_length': None,
    'late_rent_potential_label': 'None',
    'damage_to_property_label': 'None',
    'eviction_potential_label': 'None',
    'tenancy_length_label': 'None',
    'applicant_account': {'id': 'e8d7dd67-7b3f-4edb-acb9-8c28c2f10dbe', 'email': None},
    'application': {
        'id': '10bfda79-c571-49f5-8630-132ccef86592',
        'created': '2019-03-04T17:00:38.679697Z',
        'modified': '2019-03-04T17:00:38.928674Z',
        'owner': {
            'id': 'b8959d81-89aa-4e3e-9a5a-66f46bad591b',
            'email': '****************',
            'team': {
                'id': 'c7105cf6-0ae6-4d0b-9373-45f3c25b83f5',
                'name': 'Bungalow',
                'country': 'CA',
                'industry': '',
                'team_type': 'PM',
                'app_url': 'https://demo-app.certn.co/',
                'settings_config': {
                    'get_org_name': 'Bungalow',
                    'org_name': 'Bungalow',
                    'org_logo_link': None,
                    'org_primary_color': None,
                    'behavioural_test_req': False,
                    'emergency_contact_req': False,
                    'personal_ref_req': False,
                    'education_req': False,
                    'tenancy_years_amount_req': 2,
                    'tenancy_ref_amount_req': 1,
                    'tenancy_ref_email_req': False,
                    'tenancy_ref_phone_req': True,
                    'employer_records_amount_req': 1,
                    'employer_years_amount_req': 0,
                    'employer_ref_req': True,
                    'employer_ref_email_req': False,
                    'employer_ref_phone_req': False,
                    'document_required': False,
                    'cover_letter_req': False,
                    'government_id_req': True,
                    'proof_of_income_req': True,
                    'resume_req': False,
                    'personal_ref_amount_req': 1,
                    'request_base': True,
                    'request_behavioural': True,
                    'request_softcheck': True,
                    'request_equifax': False,
                    'request_identity_verification': False,
                    'request_enhanced_identity_verification': False,
                    'request_criminal_record_check': False,
                    'request_enhanced_criminal_record_check': False,
                    'request_motor_vehicle_records': False,
                    'request_education_verification': False,
                    'request_employment_verification_3_yrs': False,
                    'request_employment_verification_5_yrs': False,
                    'request_employment_verification_7_yrs': False,
                    'request_us_criminal_softcheck': False,
                    'request_us_ssn_verification': False,
                    'request_employer_references': True,
                    'request_address_references': True,
                    'exclude_softcheck_possible_matches': False,
                },
                'billing_plan': {
                    'pm_softcheck_price': '9.99',
                    'hr_softcheck_price': '9.99',
                    'pm_equifax_price': '14.99',
                    'hr_equifax_price': '14.99',
                    'pm_identity_verification_price': '1.99',
                    'hr_identity_verification_price': '1.99',
                    'pm_enhanced_identity_verification_price': '4.99',
                    'hr_enhanced_identity_verification_price': '4.99',
                    'pm_criminal_record_check_price': '29.99',
                    'hr_criminal_record_check_price': '29.99',
                    'pm_motor_vehicle_records_price': '24.99',
                    'hr_motor_vehicle_records_price': '24.99',
                    'pm_us_criminal_softcheck_price': '14.99',
                    'hr_us_criminal_softcheck_price': '14.99',
                    'pm_us_ssn_verification_price': '4.99',
                    'hr_us_ssn_verification_price': '4.99',
                    'pm_education_verification_price': '14.99',
                    'hr_education_verification_price': '14.99',
                    'pm_credential_verification_price': '14.99',
                    'hr_credential_verification_price': '14.99',
                    'pm_employment_verification_3_yrs_price': '14.99',
                    'hr_employment_verification_3_yrs_price': '14.99',
                    'pm_employment_verification_5_yrs_price': '19.99',
                    'hr_employment_verification_5_yrs_price': '19.99',
                    'pm_employment_verification_7_yrs_price': '22.99',
                    'hr_employment_verification_7_yrs_price': '22.99',
                    'pm_us_criminal_record_check_tier_1_price': '15.00',
                    'hr_us_criminal_record_check_tier_1_price': '15.00',
                    'pm_us_criminal_record_check_tier_2_price': '30.00',
                    'hr_us_criminal_record_check_tier_2_price': '30.00',
                    'pm_us_criminal_record_check_tier_3_price': '40.00',
                    'hr_us_criminal_record_check_tier_3_price': '40.00',
                    'pm_employer_references_price': '4.99',
                    'pm_address_references_price': '4.99',
                    'pm_education_references_price': '4.99',
                    'pm_credential_references_price': '4.99',
                    'hr_employer_references_price': '4.99',
                    'hr_address_references_price': '4.99',
                    'hr_education_references_price': '4.99',
                    'hr_credential_references_price': '4.99',
                },
            },
        },
        'listing': None,
        'property': None,
        'status': 'Complete',
        'applicants': [
            {
                'id': 'db13d65c-4311-46e7-8d4d-97feb693e113',
                'status': 'Analyzing',
                'first_name': 'Andrew James',
                'last_name': 'McLeod',
                'email': None,
                'certn_score': None,
                'share_of_rent': None,
                'is_cosigner': False,
                'application_url': None,
                'report_url': (
                    'https://demo-app.certn.co/pm/applications/'
                    'db13d65c-4311-46e7-8d4d-97feb693e113/'
                ),
            }
        ],
        'is_active': True,
        'is_selected': False,
        'applicant_status': 'N',
        'get_applicant_status_display': 'None',
    },
    'behavioural_result_summary': (
        'The Behavioural score is determined by analysing psychometric '
        'personality tests, social media analysis, and more.'
    ),
    'information': {
        'id': '00db959b-eb37-4e7c-83bf-8d68a6abcecd',
        'created': '2019-03-04T17:00:38.663344Z',
        'modified': '2019-03-04T17:00:38.707965Z',
        'id_url': None,
        'id_file_name': None,
        'first_name': 'Andrew James',
        'last_name': 'McLeod',
        'middle_name': None,
        'employers': [],
        'applicant_created': False,
        'applicant_verified': False,
        'educations': [],
        'cover_letter': None,
        'addresses': [
            {
                'id': '0a1e0897-8239-42c3-bba4-52839d975fd3',
                'created': '2019-03-04T17:00:38.668610Z',
                'current': True,
                'address': '3023 BODEGA ROAD',
                'unit': None,
                'rent_or_own': 'R',
                'city': 'VICTORIA',
                'province_state': 'BC',
                'country': 'CA',
                'postal_code': None,
                'cost': None,
                'start_date': None,
                'end_date': None,
                'reason_for_leaving': 'N',
                'landlords_first_name': None,
                'landlords_last_name': None,
                'landlords_phone': None,
                'landlords_email': None,
                'reference': None,
                'full_address': ' 3023 BODEGA ROAD VICTORIA BC CA',
                'information': {'first_name': 'Andrew James', 'last_name': 'McLeod'},
                'address_reference': None,
                'other_reason_for_leaving': None,
                'auto_address': None,
                'place_id': None,
                'verification': None,
                'consistency': None,
                'rent_or_own_label': 'Rent',
                'reference_verified': False,
                'other_province_state': None,
                'county': None,
            }
        ],
        'date_of_birth': '1987-03-04',
        'phone_number': None,
        'co_signer': None,
        'applicant_account': {'id': 'e8d7dd67-7b3f-4edb-acb9-8c28c2f10dbe', 'email': None},
        'co_signer_living_with_applicant': None,
        'co_signer_association': 'N',
        'co_signer_first_name': None,
        'co_signer_last_name': None,
        'co_signer_email': None,
        'co_signer_phone': None,
        'car': None,
        'car_make': None,
        'car_model': None,
        'car_year': None,
        'car_color': None,
        'health_insurance_label': 'No Coverage',
        'car_prov_state': None,
        'car_plate': None,
        'smoke': None,
        'conviction_explanation': None,
        'personal_reference_association_label': 'None',
        'bankruptcy_explanation': None,
        'eviction_explanation': None,
        'status': 'C',
        'rent_refusal_explanation': None,
        'health_insurance': 'NC',
        'feedback': None,
        'pets': None,
        'license_number': None,
        'license_valid': None,
        'license_prov_state': None,
        'pets_type': None,
        'emergency_contact': False,
        'emergency_contact_first_name': None,
        'emergency_contact_last_name': None,
        'emergency_contact_email': None,
        'expected_tenancy_length': None,
        'personal_reference': False,
        'emergency_contact_phone': None,
        'personal_reference_first_name': None,
        'personal_reference_last_name': None,
        'personal_reference_phone': None,
        'personal_reference_email': None,
        'personal_reference_association': 'N',
        'occupants': [],
        'sin_ssn': None,
        'facebook_link': None,
        'twitter_link': None,
        'linkedin_link': None,
        'googleplus_link': None,
        'desired_move_in_date': None,
        'skills': [],
        'documents': [],
        'pet_details': [],
        'rent_refusals': [],
        'bankruptcies': [],
        'evictions': [],
        'convictions': [],
        'co_signer_association_label': 'None',
        'former_names': None,
        'last_name_at_birth': None,
        'alias': None,
        'gender': None,
        'birth_city': None,
        'birth_province_state': None,
        'birth_country': None,
        'birth_other_province_state': None,
        'personal_references': [],
        'terms_accepted': False,
        'rcmp_consent_given': False,
        'co_signer_report_url': None,
        'phone': None,
    },
    'psychometric_test': None,
    'facebook': None,
    'linkedin': None,
    'informational_result': None,
    'behavioural_result': None,
    'risk_result': {
        'id': '71c4d042-c19e-46e1-a81e-3779b992ae03',
        'status': 'NONE',
        'overall_score': 'NONE',
        'risk_evaluations': [],
        'red_flags': None,
        'green_flags': None,
        'description': (
            'The social score is based on self-provided information from the '
            'applicant and an analysis of the applicants information available '
            'to Certn. This includes a criminal identity scan, social profile '
            'scan, as well as other important informational data points. *Note '
            'that when criminal identities are discovered the overall Certn '
            'score is not impacted by the results found unless the match '
            'similarity is above our confidence threshold of 95%.'
        ),
        'risk_description': (
            'The criminal identity risk is an assessment of the risk posed to '
            'assets given the results of the criminal identity scan. Please '
            'review any risk relevant information from our negative news and '
            'criminal database analysis below.'
        ),
        'similarity_description': (
            'The criminal identity similarity percentage is a comparison between '
            'the applicants self-provided information and the corresponding '
            'information we find in our databases. As a general guideline, if '
            'the results of our criminal identity scan has a similarity percentage '
            'of above 95%, Certn can confidently predict that the information '
            'presented below corresponds correctly to the applicant being '
            'screened. However, if the criminal identity scan returns results '
            'with a similarity percentage below 95%, the onus falls to the '
            'client to accurately verify the results.'
        ),
        'match_description': (
            'The criminal identity Match Score is a comparison between the '
            'applicants self-provided information and the corresponding '
            'information we find in our databases. As a general guideline, if '
            'the results of our criminal identity scan finds a "Likely Match", '
            'Certn can confidently predict that the information presented below '
            'corresponds correctly to the applicant being screened. However, if '
            'the criminal identity scan returns reasults with a Match Score of '
            '"Possible Match:", the onus falls on the client to accurately verify '
            'the results.'
        ),
    },
    'equifax_result': None,
    'identity_verification': None,
    'enhanced_identity_verification': None,
    'manual_id_verification': None,
    'late_rent_potential_description': (
        'Late rent potential risk is assessed using an analysis of an applicants '
        'financial stability and / or behavioural credibility characteristics '
        'that predicts the likelihood of late or missed payments.'
    ),
    'damage_to_property_description': (
        'Damage to property risk is assessed using an analysis of an applicants '
        'personal history and / or behavioural cleanliness and neighbour '
        'characteristics that predicts the likelihood of causing damage to property.'
    ),
    'eviction_potential_description': (
        'Early vacancy risk if assessed using an analysis of an applicants '
        'tenancy history and / or behavioural stability characteristics that '
        'predicts the likelihood of breaking a lease.'
    ),
    'applicant_result_description': (
        'Certn Rating and Certn Score is a summary assessment of the applicants '
        'unique characteristics and personal information. Andrew James McLeod has '
        'received a Certn rating of "NONE" which indicates an analysis with no '
        'potential issues. Although the score is a summary assessment, Certn '
        'still recommends you carefully review each section of this report to '
        'determine if the applicant meets your specific requirements.'
    ),
    'applicant_result_summary': (
        'The Applicant score is determined by analysing tenancy history, '
        'employment history, and more.'
    ),
    'social_result_summary': (
        'The Social score is determined by analysing criminal identity, negative '
        'news, social profile scans, and more.'
    ),
    'financial_result_summary': (
        'The Financial score is determined by analysing an Equifax credit check, '
        'and more.'
    ),
    'identity_verified': None,
    'identity_verified_summary': (
        'Upgrade Certn Report to verify Andrew James McLeods identity.'
    ),
    'request_equifax': False,
    'request_softcheck': True,
    'request_identity_verification': False,
    'request_criminal_record_check': False,
    'request_motor_vehicle_records': False,
    'request_behavioural': True,
    'request_enhanced_identity_verification': False,
    'request_education_verification': False,
    'request_credential_verification': False,
    'request_employment_verification_3_yrs': False,
    'request_employment_verification_5_yrs': False,
    'request_employment_verification_7_yrs': False,
    'can_upgrade': True,
    'reference_result': None,
    'tag': None,
    'comments': [],
    'request_us_criminal_softcheck': False,
    'request_us_ssn_verification': False,
    'country': 'CA',
    'request_employer_references': True,
    'request_address_references': True,
    'request_us_criminal_record_check_tier_1': False,
    'request_us_criminal_record_check_tier_2': False,
    'request_us_criminal_record_check_tier_3': False,
    'us_criminal_record_check_result': None,
}

INVITE_RESPONSE = {
    'id': '1be22b51-9772-4b40-b2ee-09d3595c9b72',
    'created': '2019-03-04T15:13:56.691298Z',
    'modified': '2019-03-04T15:13:56.691326Z',
    'owner': {
        'id': 'b8959d81-89aa-4e3e-9a5a-66f46bad591b',
        'email': '******************',
        'team': {
            'id': 'c7105cf6-0ae6-4d0b-9373-45f3c25b83f5',
            'name': 'Bungalow',
            'country': 'CA',
            'industry': '',
            'team_type': 'PM',
            'app_url': 'https://demo-app.certn.co/',
            'settings_config': {
                'get_org_name': 'Bungalow',
                'org_name': 'Bungalow',
                'org_logo_link': None,
                'org_primary_color': None,
                'behavioural_test_req': False,
                'emergency_contact_req': False,
                'personal_ref_req': False,
                'education_req': False,
                'tenancy_years_amount_req': 2,
                'tenancy_ref_amount_req': 1,
                'tenancy_ref_email_req': False,
                'tenancy_ref_phone_req': True,
                'employer_records_amount_req': 1,
                'employer_years_amount_req': 0,
                'employer_ref_req': True,
                'employer_ref_email_req': False,
                'employer_ref_phone_req': False,
                'document_required': False,
                'cover_letter_req': False,
                'government_id_req': True,
                'proof_of_income_req': True,
                'resume_req': False,
                'personal_ref_amount_req': 1,
                'request_base': True,
                'request_behavioural': True,
                'request_softcheck': True,
                'request_equifax': False,
                'request_identity_verification': False,
                'request_enhanced_identity_verification': False,
                'request_criminal_record_check': False,
                'request_enhanced_criminal_record_check': False,
                'request_motor_vehicle_records': False,
                'request_education_verification': False,
                'request_employment_verification_3_yrs': False,
                'request_employment_verification_5_yrs': False,
                'request_employment_verification_7_yrs': False,
                'request_us_criminal_softcheck': False,
                'request_us_ssn_verification': False,
                'request_employer_references': True,
                'request_address_references': True,
                'exclude_softcheck_possible_matches': False,
            },
            'billing_plan': {
                'pm_softcheck_price': '9.99',
                'hr_softcheck_price': '9.99',
                'pm_equifax_price': '14.99',
                'hr_equifax_price': '14.99',
                'pm_identity_verification_price': '1.99',
                'hr_identity_verification_price': '1.99',
                'pm_enhanced_identity_verification_price': '4.99',
                'hr_enhanced_identity_verification_price': '4.99',
                'pm_criminal_record_check_price': '29.99',
                'hr_criminal_record_check_price': '29.99',
                'pm_motor_vehicle_records_price': '24.99',
                'hr_motor_vehicle_records_price': '24.99',
                'pm_us_criminal_softcheck_price': '14.99',
                'hr_us_criminal_softcheck_price': '14.99',
                'pm_us_ssn_verification_price': '4.99',
                'hr_us_ssn_verification_price': '4.99',
                'pm_education_verification_price': '14.99',
                'hr_education_verification_price': '14.99',
                'pm_credential_verification_price': '14.99',
                'hr_credential_verification_price': '14.99',
                'pm_employment_verification_3_yrs_price': '14.99',
                'hr_employment_verification_3_yrs_price': '14.99',
                'pm_employment_verification_5_yrs_price': '19.99',
                'hr_employment_verification_5_yrs_price': '19.99',
                'pm_employment_verification_7_yrs_price': '22.99',
                'hr_employment_verification_7_yrs_price': '22.99',
                'pm_us_criminal_record_check_tier_1_price': '15.00',
                'hr_us_criminal_record_check_tier_1_price': '15.00',
                'pm_us_criminal_record_check_tier_2_price': '30.00',
                'hr_us_criminal_record_check_tier_2_price': '30.00',
                'pm_us_criminal_record_check_tier_3_price': '40.00',
                'hr_us_criminal_record_check_tier_3_price': '40.00',
                'pm_employer_references_price': '4.99',
                'pm_address_references_price': '4.99',
                'pm_education_references_price': '4.99',
                'pm_credential_references_price': '4.99',
                'hr_employer_references_price': '4.99',
                'hr_address_references_price': '4.99',
                'hr_education_references_price': '4.99',
                'hr_credential_references_price': '4.99',
            },
        },
    },
    'listing': None,
    'property': None,
    'status': 'Incomplete',
    'applicants': [
        {
            'id': 'a65edc29-ab29-490c-a50f-c45df9342531',
            'status': 'Pending',
            'first_name': '',
            'last_name': '',
            'email': 'fake@fake.com',
            'certn_score': None,
            'share_of_rent': None,
            'is_cosigner': False,
            'application_url': (
                'https://demo-app.certn.co/welcome/submit?'
                '&session=6018922c-f89a-4ceb-be12-06312f9519a2'
                '&token=bb54742b-8e7d-4103-bf19-78602411340b'
            ),
            'report_url': (
                'https://demo-app.certn.co/pm/applications'
                '/a65edc29-ab29-490c-a50f-c45df9342531/'
            ),
        }
    ],
    'is_active': True,
    'is_selected': False,
    'applicant_status': 'N',
    'get_applicant_status_display': 'None',
}

PROPERTY_GET_RESULT = {
    'id': 'f55abccb-ed01-4e2d-8ac8-564640306961',
    'status': 'N',
    'get_status_display': 'No Vacancy',
    'created': '2019-03-04T21:02:03.616679Z',
    'modified': '2019-03-04T21:02:03.734211Z',
    'last_updated': '2019-03-04T21:02:03.616744Z',
    'building': None,
    'building_code': None,
    'address': '123 Fakestreet',
    'city': 'Abotsford',
    'province_state': 'BC',
    'country': 'N',
    'postal_code': None,
    'is_active': True,
    'owner': {
        'id': 'b8959d81-89aa-4e3e-9a5a-66f46bad591b',
        'email': 'fake@fake.com',
        'team': {
            'id': 'c7105cf6-0ae6-4d0b-9373-45f3c25b83f5',
            'name': 'Bungalow',
            'country': 'CA',
            'industry': '',
            'team_type': 'PM',
            'app_url': 'https://demo-app.certn.co/',
            'settings_config': {
                'get_org_name': 'Bungalow',
                'org_name': 'Bungalow',
                'org_logo_link': None,
                'org_primary_color': None,
                'behavioural_test_req': False,
                'emergency_contact_req': False,
                'personal_ref_req': False,
                'education_req': False,
                'tenancy_years_amount_req': 2,
                'tenancy_ref_amount_req': 1,
                'tenancy_ref_email_req': False,
                'tenancy_ref_phone_req': True,
                'employer_records_amount_req': 1,
                'employer_years_amount_req': 0,
                'employer_ref_req': True,
                'employer_ref_email_req': False,
                'employer_ref_phone_req': False,
                'document_required': False,
                'cover_letter_req': False,
                'government_id_req': True,
                'proof_of_income_req': True,
                'resume_req': False,
                'personal_ref_amount_req': 1,
                'request_base': True,
                'request_behavioural': True,
                'request_softcheck': True,
                'request_equifax': False,
                'request_identity_verification': False,
                'request_enhanced_identity_verification': False,
                'request_criminal_record_check': False,
                'request_enhanced_criminal_record_check': False,
                'request_motor_vehicle_records': False,
                'request_education_verification': False,
                'request_employment_verification_3_yrs': False,
                'request_employment_verification_5_yrs': False,
                'request_employment_verification_7_yrs': False,
                'request_us_criminal_softcheck': False,
                'request_us_ssn_verification': False,
                'request_employer_references': True,
                'request_address_references': True,
                'exclude_softcheck_possible_matches': False,
            },
            'billing_plan': {
                'pm_softcheck_price': '9.99',
                'hr_softcheck_price': '9.99',
                'pm_equifax_price': '14.99',
                'hr_equifax_price': '14.99',
                'pm_identity_verification_price': '1.99',
                'hr_identity_verification_price': '1.99',
                'pm_enhanced_identity_verification_price': '4.99',
                'hr_enhanced_identity_verification_price': '4.99',
                'pm_criminal_record_check_price': '29.99',
                'hr_criminal_record_check_price': '29.99',
                'pm_motor_vehicle_records_price': '24.99',
                'hr_motor_vehicle_records_price': '24.99',
                'pm_us_criminal_softcheck_price': '14.99',
                'hr_us_criminal_softcheck_price': '14.99',
                'pm_us_ssn_verification_price': '4.99',
                'hr_us_ssn_verification_price': '4.99',
                'pm_education_verification_price': '14.99',
                'hr_education_verification_price': '14.99',
                'pm_credential_verification_price': '14.99',
                'hr_credential_verification_price': '14.99',
                'pm_employment_verification_3_yrs_price': '14.99',
                'hr_employment_verification_3_yrs_price': '14.99',
                'pm_employment_verification_5_yrs_price': '19.99',
                'hr_employment_verification_5_yrs_price': '19.99',
                'pm_employment_verification_7_yrs_price': '22.99',
                'hr_employment_verification_7_yrs_price': '22.99',
                'pm_us_criminal_record_check_tier_1_price': '15.00',
                'hr_us_criminal_record_check_tier_1_price': '15.00',
                'pm_us_criminal_record_check_tier_2_price': '30.00',
                'hr_us_criminal_record_check_tier_2_price': '30.00',
                'pm_us_criminal_record_check_tier_3_price': '40.00',
                'hr_us_criminal_record_check_tier_3_price': '40.00',
                'pm_employer_references_price': '4.99',
                'pm_address_references_price': '4.99',
                'pm_education_references_price': '4.99',
                'pm_credential_references_price': '4.99',
                'hr_employer_references_price': '4.99',
                'hr_address_references_price': '4.99',
                'hr_education_references_price': '4.99',
                'hr_credential_references_price': '4.99',
            },
        },
    },
    'listing_count': 0,
    'full_address': '123 Fakestreet Abotsford BC N ',
    'url_code': 'f55abccb-ed01-4e2d-8ac8-564640306961',
}

PROPERTIES_LIST_RESPONSE = {
    'count': 239,
    'next': 'http://demo-api.certn.co/api/v2/properties/?page=2',
    'previous': None,
    'results': [PROPERTY_GET_RESULT],
}

API_ERROR_SAMPLE_JSON = '''{
"error_type": "INVALID_REQUEST",
"error_message": "This is an invalid request",
"error_code": 400,
"display_message": None
}'''
